base_url = "https://karnwong.me"
title = "Karn Wong"
description = "Homepage and blog by Karn Wong"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false            # Keep this false, search is temporarily unsupported
generate_feeds = true
feed_filenames = ["rss.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "OneHalfLight", filename = "hl-light.css"},
    { theme = "OneHalfDark", filename = "hl-dark.css"},
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Karn Wong"
id = "kahnwong"
bio = "Principal Engineer (Cloud Automation & Optimization) | HashiCorp Ambassador | AWS & GCP Certified"
avatar = "img/avatar.webp"

display_id = true
display_bio = true
display_avatar = true

recent = true
recent_max = 5
recent_more_text = "more »"

sections = [
    { name = "now", path = "/now", is_external = false },
    { name = "posts", path = "/posts", is_external = false },
#    { name = "tags", path = "/tags", is_external = false },
    { name = "projects", path = "/projects", is_external = false },
    { name = "speaking", path = "/speaking", is_external = false },
     { name = "about", path = "/about", is_external = false },
     { name = "resume", path = "/resume.html", is_external = true },
    # { name = "github", path = "https://github.com/<your-username>", is_external = true },
]
blog_section_path = "/posts"

links = [
    { name = "Webring", icon = "webring", url = "https://webring.wonderful.software#karnwong.me" },
    { name = "GitHub", icon = "github", url = "https://github.com/kahnwong" },
    { name = "Bluesky", icon = "bluesky", url = "https://bsky.app/profile/karnwong.me" },
    { name = "LinkedIn", icon = "linkedin", url = "https://www.linkedin.com/in/karnsiree-w-7b535b202" },
    { name = "Email", icon = "email", url = "mailto:karn@karnwong.me" },
]

force_theme = false                   # false | "light" | "dark"
blog_categorized = true               # Whether to categorize blog posts
blur_effect = false                   # Whether to turn on blur effect on navigation bar
back_to_top = true                    # Whether to show back-to-top button on post pages
toc = true                            # Whether to show Table-of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
display_tags = true                   # Whether to display tags on post pages by default
truncate_summary = false              # Whether to truncate the summary of a post by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

footer_copyright = "© 2024 Karn Wong"
footer_credits = true                 # Whether to show "powered by zola and serene" in footer

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"

reaction = false
