# baseurl = '/'
# baseurl = "https://kahnwong.gitlab.io/blog/"
baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

disableRSS = false
rssLimit  = 20
# disableKinds = ["RSS"]

#[permalinks]
#  posts = "/posts/:year-:month-:day-:title/"

[author]
  name = "Karn Wong"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Homepage and blog by Karn Wong"
  keywords = "homepage, blog, programming, machine learning, data wrangling"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  defaultTheme = "dark"
  enableThemeToggle = true

  homeSubtitle = "Data Engineer // DevOps // SRE // Platform Engineer // Tech Lead"

   # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:contact@karnwong.me"

  [[params.social]]
    name = "github"
    url  = "https://github.com/kahnwong/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/karn-w-7b535b202"

  [params.footer]
    trademark = true
    rss = true
    author = true

    topText = []

[languages]
  [languages.en]
    title = "Karn Wong"
    subtitle = "Homepage"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"

    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#046DD6"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# And you can even create generic menu
[menu]


    [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
    weight = 1

    [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags"
    weight = 2


    [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
    weight = 3

    [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "resume.html"
    weight = 4

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight = 5

    [[menu.main]]
    identifier = "books"
    name       = "📗"
    url        = "/books"
    weight = 6

    [[menu.main]]
    identifier = "talks"
    name       = "🎙️"
    url        = "/talks"
    weight = 7


    # [[menu.main]]
    # identifier = "faq"
    # name       = "FAQ"
    # url        = "/faq"


[taxonomies]
  tag      = "tags"
  category = "categories"

[markup]
    defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
