name: Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:
env:
  PROJECT_NAME: karnwong-me
  BUILD_DIR: public
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          submodules: true
      ########################
      # build hugo
      ########################
      - name: Install hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.135.0"
          extended: true
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Bangkok"
          timezoneMacos: "Asia/Bangkok"
          timezoneWindows: "SE Asia Standard Time"
      - name: Build site
        run: |
          hugo
      ########################
      # publish
      ########################
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ${{ env.BUILD_DIR }} --project-name=${{ env.PROJECT_NAME }}
      ########################
      # healthcheck
      ########################
      - name: Install ci-cd-utils
        uses: supplypike/setup-bin@v4
        with:
          uri: https://github.com/kahnwong/ci-cd-utils/releases/download/v0.1.0/ci-cd-utils_0.1.0_linux_amd64.tar.gz
          name: ci-cd-utils
          version: 0.1.0
      - name: Healthcheck
        run: |
          ci-cd-utils healthcheck https://karnwong.me
