name: Deploy

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_KEY }}
        known_hosts: unnecessary

    - name: Install hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Setup git
      run: |
        git config --global user.name "gh actions"
        git config --global user.email "$gh-actions@users.noreply.github.com"

    - name: Deploy
      run: |
        hugo --gc --minify --cleanDestinationDir
        cd public
        git init
        git remote add origin git@github.com:kahnwong/kahnwong.github.io.git
        git add -A
        git checkout -b master
        git commit -m "Automated deployment @ $(date '+%Y-%m-%d %H:%M:%S') ${TZ}"
        git push -f origin master
