name: Deploy

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Set timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Bangkok"
        timezoneMacos: "Asia/Bangkok"
        timezoneWindows: "SE Asia Standard Time"

    - name: Build site
      run: |
        hugo --gc --minify --cleanDestinationDir

    - name: Deploy site
      with:
        build-dir: public
        deploy-branch: gh-pages
      uses:  NickSchimek/deploy_jamstack_action@main
